default: test
set fallback
VENV := env_var_or_default("VENV", ".venv")
VENV_BIN := VENV / "bin"

@venv:
  python3 -c "import virtualenv" || python3 -m pip --quiet install virtualenv
  python3 -m virtualenv {{VENV}} --quiet
  {{VENV_BIN}}/python -m pip --quiet install poetry

## Set up virtual environment and install requirements
@requirements: venv
  {{VENV_BIN}}/poetry install

test *args: requirements
  {{VENV_BIN}}/poetry -C tests run pytest --rootdir={{justfile_directory()}} {{ if args == "" {'tests'} else {args} }}
