set fallback
VENV := ".venv"
VENV_BIN := ".venv/bin"


@venv:
	@python3 -m pip install virtualenv > /dev/null
	@python3 -m virtualenv {{VENV}} > /dev/null

## Set up virtual environment and install requirements
@requirements: venv
	{{VENV_BIN}}/python -m pip install --upgrade pip > /dev/null
	{{VENV_BIN}}/pip install -r requirements.txt > /dev/null

## Compile and install py-glaredb for development
build *args: requirements
	@unset CONDA_PREFIX
	{{VENV_BIN}}/maturin develop {{args}}

test: requirements
	{{VENV_BIN}}/pytest -s

## Run autoformatting and linting
fmt: venv  
	{{VENV_BIN}}/ruff .
	{{VENV_BIN}}/black .
	{{VENV_BIN}}/blackdoc .
	cargo fmt --all
	-$(VENV_BIN)/mypy

example path: requirements
	{{VENV_BIN}}/python examples/{{path}}.py