set fallback
VENV := env_var_or_default("VENV", ".venv")
VENV_BIN := VENV / "bin"

@venv:
  if python3 -c "import virtualenv"; then python3 -m virtualenv {{VENV}}; else python3 -m venv {{VENV}}; fi
  {{VENV_BIN}}/python -m pip install --upgrade pip
  {{VENV_BIN}}/pip install -r requirements.txt

## Compile and install py-glaredb for development
build *args:
  @unset CONDA_PREFIX
  {{VENV_BIN}}/maturin develop {{args}}

test:
  {{VENV_BIN}}/pytest --rootdir={{justfile_directory()}}

## Run autoformatting and linting
fmt:
  {{VENV_BIN}}/ruff .
  {{VENV_BIN}}/mypy
  cargo fmt --all

example path:
  {{VENV_BIN}}/python examples/{{path}}.py
